INSERT INTO instruments (symbol, name, exchange, sector, industry, lot_size, tick_size, created_at)
VALUES
('AAPL', 'Apple Inc.', 'NASDAQ', 'Technology', 'Consumer Electronics', 1, 0.01, NULL),
('MSFT', 'Microsoft Corporation', 'NASDAQ', 'Technology', 'Software - Infrastructure', 1, 0.01, NULL),
('NVDA', 'NVIDIA Corporation', 'NASDAQ', 'Technology', 'Semiconductors', 1, 0.01, NULL),
('AMZN', 'Amazon.com, Inc.', 'NASDAQ', 'Consumer Cyclical', 'Internet Retail', 1, 0.01, NULL),
('META', 'Meta Platforms, Inc.', 'NASDAQ', 'Communication Services', 'Internet Content & Information', 1, 0.01, NULL),
('GOOGL', 'Alphabet Inc.', 'NASDAQ', 'Communication Services', 'Internet Content & Information', 1, 0.01, NULL),
('GOOG', 'Alphabet Inc.', 'NASDAQ', 'Communication Services', 'Internet Content & Information', 1, 0.01, NULL),
('BRK-B', 'Berkshire Hathaway Inc.', 'NYSE', 'Financial Services', 'Insurance - Diversified', 1, 0.01, NULL),
('LLY', 'Eli Lilly and Company', 'NYSE', 'Healthcare', 'Drug Manufacturers - General', 1, 0.01, NULL),
('TSLA', 'Tesla, Inc.', 'NASDAQ', 'Consumer Cyclical', 'Auto Manufacturers', 1, 0.01, NULL),
('AVGO', 'Broadcom Inc.', 'NASDAQ', 'Technology', 'Semiconductors', 1, 0.01, NULL),
('JPM', 'JPMorgan Chase & Co.', 'NYSE', 'Financial Services', 'Banks - Diversified', 1, 0.01, NULL),
('V', 'Visa Inc.', 'NYSE', 'Financial Services', 'Credit Services', 1, 0.01, NULL),
('UNH', 'UnitedHealth Group Incorporated', 'NYSE', 'Healthcare', 'Healthcare Plans', 1, 0.01, NULL),
('XOM', 'Exxon Mobil Corporation', 'NYSE', 'Energy', 'Oil & Gas Integrated', 1, 0.01, NULL),
('WMT', 'Walmart Inc.', 'NASDAQ', 'Consumer Defensive', 'Discount Stores', 1, 0.01, NULL),
('MA', 'Mastercard Incorporated', 'NYSE', 'Financial Services', 'Credit Services', 1, 0.01, NULL),
('JNJ', 'Johnson & Johnson', 'NYSE', 'Healthcare', 'Drug Manufacturers - General', 1, 0.01, NULL),
('PG', 'The Procter & Gamble Company', 'NYSE', 'Consumer Defensive', 'Household & Personal Products', 1, 0.01, NULL),
('HD', 'The Home Depot, Inc.', 'NYSE', 'Consumer Cyclical', 'Home Improvement Retail', 1, 0.01, NULL),
('COST', 'Costco Wholesale Corporation', 'NASDAQ', 'Consumer Defensive', 'Discount Stores', 1, 0.01, NULL),
('BAC', 'Bank of America Corporation', 'NYSE', 'Financial Services', 'Banks - Diversified', 1, 0.01, NULL),
('MRK', 'Merck & Co., Inc.', 'NYSE', 'Healthcare', 'Drug Manufacturers - General', 1, 0.01, NULL),
('ABBV', 'AbbVie Inc.', 'NYSE', 'Healthcare', 'Drug Manufacturers - General', 1, 0.01, NULL),
('CVX', 'Chevron Corporation', 'NYSE', 'Energy', 'Oil & Gas Integrated', 1, 0.01, NULL),
('PEP', 'PepsiCo, Inc.', 'NASDAQ', 'Consumer Defensive', 'Beverages - Non-Alcoholic', 1, 0.01, NULL),
('KO', 'The Coca-Cola Company', 'NYSE', 'Consumer Defensive', 'Beverages - Non-Alcoholic', 1, 0.01, NULL),
('ADBE', 'Adobe Inc.', 'NASDAQ', 'Technology', 'Software - Application', 1, 0.01, NULL),
('ORCL', 'Oracle Corporation', 'NYSE', 'Technology', 'Software - Infrastructure', 1, 0.01, NULL),
('NFLX', 'Netflix, Inc.', 'NASDAQ', 'Communication Services', 'Entertainment', 1, 0.01, NULL),
('TMO', 'Thermo Fisher Scientific Inc.', 'NYSE', 'Healthcare', 'Diagnostics & Research', 1, 0.01, NULL),
('LIN', 'Linde plc', 'NASDAQ', 'Basic Materials', 'Specialty Chemicals', 1, 0.01, NULL),
('ACN', 'Accenture plc', 'NYSE', 'Technology', 'Information Technology Services', 1, 0.01, NULL),
('MCD', 'McDonald''s Corporation', 'NYSE', 'Consumer Cyclical', 'Restaurants', 1, 0.01, NULL),
('ABT', 'Abbott Laboratories', 'NYSE', 'Healthcare', 'Medical Devices', 1, 0.01, NULL),
('WFC', 'Wells Fargo & Company', 'NYSE', 'Financial Services', 'Banks - Diversified', 1, 0.01, NULL),
('DHR', 'Danaher Corporation', 'NYSE', 'Healthcare', 'Diagnostics & Research', 1, 0.01, NULL),
('CSCO', 'Cisco Systems, Inc.', 'NASDAQ', 'Technology', 'Communication Equipment', 1, 0.01, NULL),
('CRM', 'Salesforce, Inc.', 'NYSE', 'Technology', 'Software - Application', 1, 0.01, NULL),
('TXN', 'Texas Instruments Incorporated', 'NASDAQ', 'Technology', 'Semiconductors', 1, 0.01, NULL),
('PM', 'Philip Morris International Inc.', 'NYSE', 'Consumer Defensive', 'Tobacco', 1, 0.01, NULL),
('INTC', 'Intel Corporation', 'NASDAQ', 'Technology', 'Semiconductors', 1, 0.01, NULL),
('VZ', 'Verizon Communications Inc.', 'NYSE', 'Communication Services', 'Telecom Services', 1, 0.01, NULL),
('UPS', 'United Parcel Service, Inc.', 'NYSE', 'Industrials', 'Integrated Freight & Logistics', 1, 0.01, NULL),
('NEE', 'NextEra Energy, Inc.', 'NYSE', 'Utilities', 'Utilities - Regulated Electric', 1, 0.01, NULL),
('IBM', 'International Business Machines Corporation', 'NYSE', 'Technology', 'Information Technology Services', 1, 0.01, NULL),
('UNP', 'Union Pacific Corporation', 'NYSE', 'Industrials', 'Railroads', 1, 0.01, NULL),
('HON', 'Honeywell International Inc.', 'NASDAQ', 'Industrials', 'Conglomerates', 1, 0.01, NULL),
('QCOM', 'QUALCOMM Incorporated', 'NASDAQ', 'Technology', 'Semiconductors', 1, 0.01, NULL),
('AMGN', 'Amgen Inc.', 'NASDAQ', 'Healthcare', 'Drug Manufacturers - General', 1, 0.01, NULL),
('LOW', 'Lowe''s Companies, Inc.', 'NYSE', 'Consumer Cyclical', 'Home Improvement Retail', 1, 0.01, NULL),
('CAT', 'Caterpillar Inc.', 'NYSE', 'Industrials', 'Farm & Heavy Construction Machinery', 1, 0.01, NULL),
('MS', 'Morgan Stanley', 'NYSE', 'Financial Services', 'Capital Markets', 1, 0.01, NULL),
('GS', 'The Goldman Sachs Group, Inc.', 'NYSE', 'Financial Services', 'Capital Markets', 1, 0.01, NULL),
('SPGI', 'S&P Global Inc.', 'NYSE', 'Financial Services', 'Financial Data & Stock Exchanges', 1, 0.01, NULL),
('RTX', 'RTX Corporation', 'NYSE', 'Industrials', 'Aerospace & Defense', 1, 0.01, NULL),
('BLK', 'BlackRock, Inc.', 'NYSE', 'Financial Services', 'Asset Management', 1, 0.01, NULL),
('AMD', 'Advanced Micro Devices, Inc.', 'NASDAQ', 'Technology', 'Semiconductors', 1, 0.01, NULL),
('SCHW', 'The Charles Schwab Corporation', 'NYSE', 'Financial Services', 'Capital Markets', 1, 0.01, NULL),
('AMAT', 'Applied Materials, Inc.', 'NASDAQ', 'Technology', 'Semiconductor Equipment & Materials', 1, 0.01, NULL),
('GE', 'GE Aerospace', 'NYSE', 'Industrials', 'Aerospace & Defense', 1, 0.01, NULL),
('MDT', 'Medtronic plc', 'NYSE', 'Healthcare', 'Medical Devices', 1, 0.01, NULL),
('ISRG', 'Intuitive Surgical, Inc.', 'NASDAQ', 'Healthcare', 'Medical Instruments & Supplies', 1, 0.01, NULL),
('BKNG', 'Booking Holdings Inc.', 'NASDAQ', 'Consumer Cyclical', 'Travel Services', 1, 0.01, NULL),
('SBUX', 'Starbucks Corporation', 'NASDAQ', 'Consumer Cyclical', 'Restaurants', 1, 0.01, NULL),
('PLD', 'Prologis, Inc.', 'NYSE', 'Real Estate', 'REIT - Industrial', 1, 0.01, NULL),
('DE', 'Deere & Company', 'NYSE', 'Industrials', 'Farm & Heavy Construction Machinery', 1, 0.01, NULL),
('LMT', 'Lockheed Martin Corporation', 'NYSE', 'Industrials', 'Aerospace & Defense', 1, 0.01, NULL),
('ELV', 'Elevance Health, Inc.', 'NYSE', 'Healthcare', 'Healthcare Plans', 1, 0.01, NULL),
('T', 'AT&T Inc.', 'NYSE', 'Communication Services', 'Telecom Services', 1, 0.01, NULL),
('NOW', 'ServiceNow, Inc.', 'NYSE', 'Technology', 'Software - Application', 1, 0.01, NULL),
('ADI', 'Analog Devices, Inc.', 'NASDAQ', 'Technology', 'Semiconductors', 1, 0.01, NULL),
('MO', 'Altria Group, Inc.', 'NYSE', 'Consumer Defensive', 'Tobacco', 1, 0.01, NULL),
('SYK', 'Stryker Corporation', 'NYSE', 'Healthcare', 'Medical Devices', 1, 0.01, NULL),
('CI', 'The Cigna Group', 'NYSE', 'Healthcare', 'Healthcare Plans', 1, 0.01, NULL),
('MDLZ', 'Mondelez International, Inc.', 'NASDAQ', 'Consumer Defensive', 'Confectioners', 1, 0.01, NULL),
('CB', 'Chubb Limited', 'NYSE', 'Financial Services', 'Insurance - Property & Casualty', 1, 0.01, NULL),
('MMC', NULL, NULL, NULL, NULL, 1, 0.01, NULL),
('REGN', 'Regeneron Pharmaceuticals, Inc.', 'NASDAQ', 'Healthcare', 'Biotechnology', 1, 0.01, NULL),
('GILD', 'Gilead Sciences, Inc.', 'NASDAQ', 'Healthcare', 'Drug Manufacturers - General', 1, 0.01, NULL),
('C', 'Citigroup Inc.', 'NYSE', 'Financial Services', 'Banks - Diversified', 1, 0.01, NULL),
('ADP', 'Automatic Data Processing, Inc.', 'NASDAQ', 'Technology', 'Software - Application', 1, 0.01, NULL),
('PFE', 'Pfizer Inc.', 'NYSE', 'Healthcare', 'Drug Manufacturers - General', 1, 0.01, NULL),
('VRTX', 'Vertex Pharmaceuticals Incorporated', 'NASDAQ', 'Healthcare', 'Biotechnology', 1, 0.01, NULL),
('CL', 'Colgate-Palmolive Company', 'NYSE', 'Consumer Defensive', 'Household & Personal Products', 1, 0.01, NULL),
('ZTS', 'Zoetis Inc.', 'NYSE', 'Healthcare', 'Drug Manufacturers - Specialty & Generic', 1, 0.01, NULL),
('CSX', 'CSX Corporation', 'NASDAQ', 'Industrials', 'Railroads', 1, 0.01, NULL),
('BDX', 'Becton, Dickinson and Company', 'NYSE', 'Healthcare', 'Medical Instruments & Supplies', 1, 0.01, NULL),
('MU', 'Micron Technology, Inc.', 'NASDAQ', 'Technology', 'Semiconductors', 1, 0.01, NULL),
('PANW', 'Palo Alto Networks, Inc.', 'NASDAQ', 'Technology', 'Software - Infrastructure', 1, 0.01, NULL),
('FDX', 'FedEx Corporation', 'NYSE', 'Industrials', 'Integrated Freight & Logistics', 1, 0.01, NULL),
('SO', 'The Southern Company', 'NYSE', 'Utilities', 'Utilities - Regulated Electric', 1, 0.01, NULL),
('EQIX', 'Equinix, Inc.', 'NASDAQ', 'Real Estate', 'REIT - Specialty', 1, 0.01, NULL),
('ICE', 'Intercontinental Exchange, Inc.', 'NYSE', 'Financial Services', 'Financial Data & Stock Exchanges', 1, 0.01, NULL),
('ITW', 'Illinois Tool Works Inc.', 'NYSE', 'Industrials', 'Specialty Industrial Machinery', 1, 0.01, NULL),
('SLB', 'SLB N.V.', 'NYSE', 'Energy', 'Oil & Gas Equipment & Services', 1, 0.01, NULL),
('APD', 'Air Products and Chemicals, Inc.', 'NYSE', 'Basic Materials', 'Specialty Chemicals', 1, 0.01, NULL),
('GM', 'General Motors Company', 'NYSE', 'Consumer Cyclical', 'Auto Manufacturers', 1, 0.01, NULL),
('USB', 'U.S. Bancorp', 'NYSE', 'Financial Services', 'Banks - Regional', 1, 0.01, NULL),
('SHW', 'The Sherwin-Williams Company', 'NYSE', 'Basic Materials', 'Specialty Chemicals', 1, 0.01, NULL),
('TJX', 'The TJX Companies, Inc.', 'NYSE', 'Consumer Cyclical', 'Apparel Retail', 1, 0.01, NULL),
('NSC', 'Norfolk Southern Corporation', 'NYSE', 'Industrials', 'Railroads', 1, 0.01, NULL),
('WM', 'Waste Management, Inc.', 'NYSE', 'Industrials', 'Waste Management', 1, 0.01, NULL),
('GD', 'General Dynamics Corporation', 'NYSE', 'Industrials', 'Aerospace & Defense', 1, 0.01, NULL),
('AON', 'Aon plc', 'NYSE', 'Financial Services', 'Insurance Brokers', 1, 0.01, NULL),
('DUK', 'Duke Energy Corporation', 'NYSE', 'Utilities', 'Utilities - Regulated Electric', 1, 0.01, NULL),
('PNC', 'The PNC Financial Services Group, Inc.', 'NYSE', 'Financial Services', 'Banks - Regional', 1, 0.01, NULL),
('TGT', 'Target Corporation', 'NYSE', 'Consumer Defensive', 'Discount Stores', 1, 0.01, NULL),
('FIS', 'Fidelity National Information Services, Inc.', 'NYSE', 'Technology', 'Information Technology Services', 1, 0.01, NULL),
('HCA', 'HCA Healthcare, Inc.', 'NYSE', 'Healthcare', 'Medical Care Facilities', 1, 0.01, NULL),
('EOG', 'EOG Resources, Inc.', 'NYSE', 'Energy', 'Oil & Gas E&P', 1, 0.01, NULL),
('ADSK', 'Autodesk, Inc.', 'NASDAQ', 'Technology', 'Software - Application', 1, 0.01, NULL),
('MAR', 'Marriott International, Inc.', 'NASDAQ', 'Consumer Cyclical', 'Lodging', 1, 0.01, NULL),
('LRCX', 'Lam Research Corporation', 'NASDAQ', 'Technology', 'Semiconductor Equipment & Materials', 1, 0.01, NULL),
('AIG', 'American International Group, Inc.', 'NYSE', 'Financial Services', 'Insurance - Diversified', 1, 0.01, NULL),
('PGR', 'The Progressive Corporation', 'NYSE', 'Financial Services', 'Insurance - Property & Casualty', 1, 0.01, NULL),
('MPC', 'Marathon Petroleum Corporation', 'NYSE', 'Energy', 'Oil & Gas Refining & Marketing', 1, 0.01, NULL),
('KLAC', 'KLA Corporation', 'NASDAQ', 'Technology', 'Semiconductor Equipment & Materials', 1, 0.01, NULL),
('FISV', 'Fiserv, Inc.', 'NASDAQ', NULL, NULL, 1, 0.01, NULL),
('ETN', 'Eaton Corporation plc', 'NYSE', 'Industrials', 'Specialty Industrial Machinery', 1, 0.01, NULL),
('PH', 'Parker-Hannifin Corporation', 'NYSE', 'Industrials', 'Specialty Industrial Machinery', 1, 0.01, NULL),
('CME', 'CME Group Inc.', 'NASDAQ', 'Financial Services', 'Financial Data & Stock Exchanges', 1, 0.01, NULL),
('HUM', 'Humana Inc.', 'NYSE', 'Healthcare', 'Healthcare Plans', 1, 0.01, NULL),
('AEP', 'American Electric Power Company, Inc.', 'NASDAQ', 'Utilities', 'Utilities - Regulated Electric', 1, 0.01, NULL),
('ROP', 'Roper Technologies, Inc.', 'NASDAQ', 'Technology', 'Software - Application', 1, 0.01, NULL),
('NXPI', 'NXP Semiconductors N.V.', 'NASDAQ', 'Technology', 'Semiconductors', 1, 0.01, NULL),
('TRV', 'The Travelers Companies, Inc.', 'NYSE', 'Financial Services', 'Insurance - Property & Casualty', 1, 0.01, NULL),
('KDP', 'Keurig Dr Pepper Inc.', 'NASDAQ', 'Consumer Defensive', 'Beverages - Non-Alcoholic', 1, 0.01, NULL),
('PSA', 'Public Storage', 'NYSE', 'Real Estate', 'REIT - Industrial', 1, 0.01, NULL),
('AZO', 'AutoZone, Inc.', 'NYSE', 'Consumer Cyclical', 'Auto Parts', 1, 0.01, NULL),
('D', 'Dominion Energy, Inc.', 'NYSE', 'Utilities', 'Utilities - Regulated Electric', 1, 0.01, NULL),
('MCO', 'Moody''s Corporation', 'NYSE', 'Financial Services', 'Financial Data & Stock Exchanges', 1, 0.01, NULL),
('AFL', 'Aflac Incorporated', 'NYSE', 'Financial Services', 'Insurance - Life', 1, 0.01, NULL),
('OXY', 'Occidental Petroleum Corporation', 'NYSE', 'Energy', 'Oil & Gas E&P', 1, 0.01, NULL),
('CTAS', 'Cintas Corporation', 'NASDAQ', 'Industrials', 'Specialty Business Services', 1, 0.01, NULL),
('SRE', 'Sempra', 'NYSE', 'Utilities', 'Utilities - Diversified', 1, 0.01, NULL),
('MSCI', 'MSCI Inc.', 'NYSE', 'Financial Services', 'Financial Data & Stock Exchanges', 1, 0.01, NULL),
('KMB', 'Kimberly-Clark Corporation', 'NASDAQ', 'Consumer Defensive', 'Household & Personal Products', 1, 0.01, NULL),
('HLT', 'Hilton Worldwide Holdings Inc.', 'NYSE', 'Consumer Cyclical', 'Lodging', 1, 0.01, NULL),
('PAYX', 'Paychex, Inc.', 'NASDAQ', 'Technology', 'Software - Application', 1, 0.01, NULL),
('CMCSA', 'Comcast Corporation', 'NASDAQ', 'Communication Services', 'Telecom Services', 1, 0.01, NULL),
('DG', 'Dollar General Corporation', 'NYSE', 'Consumer Defensive', 'Discount Stores', 1, 0.01, NULL),
('ORLY', 'O''Reilly Automotive, Inc.', 'NASDAQ', 'Consumer Cyclical', 'Auto Parts', 1, 0.01, NULL),
('CNC', 'Centene Corporation', 'NYSE', 'Healthcare', 'Healthcare Plans', 1, 0.01, NULL),
('IDXX', 'IDEXX Laboratories, Inc.', 'NASDAQ', 'Healthcare', 'Diagnostics & Research', 1, 0.01, NULL),
('FTNT', 'Fortinet, Inc.', 'NASDAQ', 'Technology', 'Software - Infrastructure', 1, 0.01, NULL),
('LHX', 'L3Harris Technologies, Inc.', 'NYSE', 'Industrials', 'Aerospace & Defense', 1, 0.01, NULL),
('TEL', 'TE Connectivity plc', 'NYSE', 'Technology', 'Electronic Components', 1, 0.01, NULL),
('PCAR', 'PACCAR Inc', 'NASDAQ', 'Industrials', 'Farm & Heavy Construction Machinery', 1, 0.01, NULL),
('MNST', 'Monster Beverage Corporation', 'NASDAQ', 'Consumer Defensive', 'Beverages - Non-Alcoholic', 1, 0.01, NULL),
('ALL', 'The Allstate Corporation', 'NYSE', 'Financial Services', 'Insurance - Property & Casualty', 1, 0.01, NULL),
('KMI', 'Kinder Morgan, Inc.', 'NYSE', 'Energy', 'Oil & Gas Midstream', 1, 0.01, NULL),
('NOC', 'Northrop Grumman Corporation', 'NYSE', 'Industrials', 'Aerospace & Defense', 1, 0.01, NULL),
('EXC', 'Exelon Corporation', 'NASDAQ', 'Utilities', 'Utilities - Regulated Electric', 1, 0.01, NULL),
('A', 'Agilent Technologies, Inc.', 'NYSE', 'Healthcare', 'Diagnostics & Research', 1, 0.01, NULL),
('ROST', 'Ross Stores, Inc.', 'NASDAQ', 'Consumer Cyclical', 'Apparel Retail', 1, 0.01, NULL),
('VLO', 'Valero Energy Corporation', 'NYSE', 'Energy', 'Oil & Gas Refining & Marketing', 1, 0.01, NULL),
('PRU', 'Prudential Financial, Inc.', 'NYSE', 'Financial Services', 'Insurance - Life', 1, 0.01, NULL),
('GPN', 'Global Payments Inc.', 'NYSE', 'Industrials', 'Specialty Business Services', 1, 0.01, NULL),
('DLR', 'Digital Realty Trust, Inc.', 'NYSE', 'Real Estate', 'REIT - Specialty', 1, 0.01, NULL),
('HPQ', 'HP Inc.', 'NYSE', 'Technology', 'Computer Hardware', 1, 0.01, NULL),
('SYY', 'Sysco Corporation', 'NYSE', 'Consumer Defensive', 'Food Distribution', 1, 0.01, NULL),
('ED', 'Consolidated Edison, Inc.', 'NYSE', 'Utilities', 'Utilities - Regulated Electric', 1, 0.01, NULL),
('MET', 'MetLife, Inc.', 'NYSE', 'Financial Services', 'Insurance - Life', 1, 0.01, NULL),
('HES', NULL, NULL, NULL, NULL, 1, 0.01, NULL),
('BMY', 'Bristol-Myers Squibb Company', 'NYSE', 'Healthcare', 'Drug Manufacturers - General', 1, 0.01, NULL),
('KR', 'The Kroger Co.', 'NYSE', 'Consumer Defensive', 'Grocery Stores', 1, 0.01, NULL),
('PPG', 'PPG Industries, Inc.', 'NYSE', 'Basic Materials', 'Specialty Chemicals', 1, 0.01, NULL),
('AEE', 'Ameren Corporation', 'NYSE', 'Utilities', 'Utilities - Regulated Electric', 1, 0.01, NULL),
('DHI', 'D.R. Horton, Inc.', 'NYSE', 'Consumer Cyclical', 'Residential Construction', 1, 0.01, NULL),
('LEN', 'Lennar Corporation', 'NYSE', 'Consumer Cyclical', 'Residential Construction', 1, 0.01, NULL),
('WMB', 'The Williams Companies, Inc.', 'NYSE', 'Energy', 'Oil & Gas Midstream', 1, 0.01, NULL),
('ECL', 'Ecolab Inc.', 'NYSE', 'Basic Materials', 'Specialty Chemicals', 1, 0.01, NULL),
('STZ', 'Constellation Brands, Inc.', 'NYSE', 'Consumer Defensive', 'Beverages - Brewers', 1, 0.01, NULL),
('MCK', 'McKesson Corporation', 'NYSE', 'Healthcare', 'Medical Distribution', 1, 0.01, NULL),
('CDNS', 'Cadence Design Systems, Inc.', 'NASDAQ', 'Technology', 'Software - Application', 1, 0.01, NULL),
('CTSH', 'Cognizant Technology Solutions Corporation', 'NASDAQ', 'Technology', 'Information Technology Services', 1, 0.01, NULL),
('ADM', 'Archer-Daniels-Midland Company', 'NYSE', 'Consumer Defensive', 'Farm Products', 1, 0.01, NULL),
('ILMN', 'Illumina, Inc.', 'NASDAQ', 'Healthcare', 'Diagnostics & Research', 1, 0.01, NULL),
('TT', 'Trane Technologies plc', 'NYSE', 'Industrials', 'Building Products & Equipment', 1, 0.01, NULL),
('OTIS', 'Otis Worldwide Corporation', 'NYSE', 'Industrials', 'Specialty Industrial Machinery', 1, 0.01, NULL),
('RSG', 'Republic Services, Inc.', 'NYSE', 'Industrials', 'Waste Management', 1, 0.01, NULL),
('F', 'Ford Motor Company', 'NYSE', 'Consumer Cyclical', 'Auto Manufacturers', 1, 0.01, NULL),
('KHC', 'The Kraft Heinz Company', 'NASDAQ', 'Consumer Defensive', 'Packaged Foods', 1, 0.01, NULL),
('BKR', 'Baker Hughes Company', 'NASDAQ', 'Energy', 'Oil & Gas Equipment & Services', 1, 0.01, NULL),
('GLW', 'Corning Incorporated', 'NYSE', 'Technology', 'Electronic Components', 1, 0.01, NULL),
('VRSK', 'Verisk Analytics, Inc.', 'NASDAQ', 'Industrials', 'Consulting Services', 1, 0.01, NULL),
('MTB', 'M&T Bank Corporation', 'NYSE', 'Financial Services', 'Banks - Regional', 1, 0.01, NULL),
('WELL', 'Welltower Inc.', 'NYSE', 'Real Estate', 'REIT - Healthcare Facilities', 1, 0.01, NULL),
('PEG', 'Public Service Enterprise Group Incorporated', 'NYSE', 'Utilities', 'Utilities - Regulated Electric', 1, 0.01, NULL),
('XEL', 'Xcel Energy Inc.', 'NASDAQ', 'Utilities', 'Utilities - Regulated Electric', 1, 0.01, NULL),
('ALB', 'Albemarle Corporation', 'NYSE', 'Basic Materials', 'Specialty Chemicals', 1, 0.01, NULL),
('DLTR', 'Dollar Tree, Inc.', 'NASDAQ', 'Consumer Defensive', 'Discount Stores', 1, 0.01, NULL),
('HIG', 'The Hartford Insurance Group, Inc.', 'NYSE', 'Financial Services', 'Insurance - Diversified', 1, 0.01, NULL),
('KEYS', 'Keysight Technologies, Inc.', 'NYSE', 'Technology', 'Scientific & Technical Instruments', 1, 0.01, NULL),
('VICI', 'VICI Properties Inc.', 'NYSE', 'Real Estate', 'REIT - Diversified', 1, 0.01, NULL),
('ODFL', 'Old Dominion Freight Line, Inc.', 'NASDAQ', 'Industrials', 'Trucking', 1, 0.01, NULL),
('WBA', NULL, NULL, NULL, NULL, 1, 0.01, NULL),
('LUV', 'Southwest Airlines Co.', 'NYSE', 'Industrials', 'Airlines', 1, 0.01, NULL),
('ZBH', 'Zimmer Biomet Holdings, Inc.', 'NYSE', 'Healthcare', 'Medical Devices', 1, 0.01, NULL),
('DTE', 'DTE Energy Company', 'NYSE', 'Utilities', 'Utilities - Regulated Electric', 1, 0.01, NULL),
('ES', 'Eversource Energy', 'NYSE', 'Utilities', 'Utilities - Regulated Electric', 1, 0.01, NULL),
('PPL', 'PPL Corporation', 'NYSE', 'Utilities', 'Utilities - Regulated Electric', 1, 0.01, NULL),
('AAL', 'American Airlines Group Inc.', 'NASDAQ', 'Industrials', 'Airlines', 1, 0.01, NULL),
('DAL', 'Delta Air Lines, Inc.', 'NYSE', 'Industrials', 'Airlines', 1, 0.01, NULL),
('UAL', 'United Airlines Holdings, Inc.', 'NASDAQ', 'Industrials', 'Airlines', 1, 0.01, NULL),
('CCL', 'Carnival Corporation Ltd.', 'NYSE', 'Consumer Cyclical', 'Travel Services', 1, 0.01, NULL),
('RCL', 'Royal Caribbean Cruises Ltd.', 'NYSE', 'Consumer Cyclical', 'Travel Services', 1, 0.01, NULL),
('NCLH', 'Norwegian Cruise Line Holdings Ltd.', 'NYSE', 'Consumer Cyclical', 'Travel Services', 1, 0.01, NULL),
('MGM', 'MGM Resorts International', 'NYSE', 'Consumer Cyclical', 'Resorts & Casinos', 1, 0.01, NULL),
('LVS', 'Las Vegas Sands Corp.', 'NYSE', 'Consumer Cyclical', 'Resorts & Casinos', 1, 0.01, NULL),
('WYNN', 'Wynn Resorts, Limited', 'NASDAQ', 'Consumer Cyclical', 'Resorts & Casinos', 1, 0.01, NULL),
('EXPE', 'Expedia Group, Inc.', 'NASDAQ', 'Consumer Cyclical', 'Travel Services', 1, 0.01, NULL),
('EBAY', 'eBay Inc.', 'NASDAQ', 'Consumer Cyclical', 'Internet Retail', 1, 0.01, NULL),
('BK', 'The Bank of New York Mellon Corporation', 'NYSE', 'Financial Services', 'Banks - Diversified', 1, 0.01, NULL),
('STT', 'State Street Corporation', 'NYSE', 'Financial Services', 'Asset Management', 1, 0.01, NULL),
('FITB', 'Fifth Third Bancorp', 'NASDAQ', 'Financial Services', 'Banks - Regional', 1, 0.01, NULL),
('RF', 'Regions Financial Corporation', 'NYSE', 'Financial Services', 'Banks - Regional', 1, 0.01, NULL),
('HBAN', 'Huntington Bancshares Incorporated', 'NASDAQ', 'Financial Services', 'Banks - Regional', 1, 0.01, NULL),
('KEY', 'KeyCorp', 'NYSE', 'Financial Services', 'Banks - Regional', 1, 0.01, NULL),
('CFG', 'Citizens Financial Group, Inc.', 'NYSE', 'Financial Services', 'Banks - Regional', 1, 0.01, NULL),
('ALLY', 'Ally Financial Inc.', 'NYSE', 'Financial Services', 'Credit Services', 1, 0.01, NULL),
('COF', 'Capital One Financial Corporation', 'NYSE', 'Financial Services', 'Credit Services', 1, 0.01, NULL),
('DFS', NULL, NULL, NULL, NULL, 1, 0.01, NULL),
('SYF', 'Synchrony Financial', 'NYSE', 'Financial Services', 'Credit Services', 1, 0.01, NULL),
('VTRS', 'Viatris Inc.', 'NASDAQ', 'Healthcare', 'Drug Manufacturers - Specialty & Generic', 1, 0.01, NULL),
('BIIB', 'Biogen Inc.', 'NASDAQ', 'Healthcare', 'Drug Manufacturers - General', 1, 0.01, NULL),
('MRNA', 'Moderna, Inc.', 'NASDAQ', 'Healthcare', 'Biotechnology', 1, 0.01, NULL),
('BAX', 'Baxter International Inc.', 'NYSE', 'Healthcare', 'Medical Instruments & Supplies', 1, 0.01, NULL),
('EW', 'Edwards Lifesciences Corporation', 'NYSE', 'Healthcare', 'Medical Devices', 1, 0.01, NULL),
('ALGN', 'Align Technology, Inc.', 'NASDAQ', 'Healthcare', 'Medical Instruments & Supplies', 1, 0.01, NULL),
('STE', 'STERIS plc', 'NYSE', 'Healthcare', 'Medical Devices', 1, 0.01, NULL),
('MTD', 'Mettler-Toledo International Inc.', 'NYSE', 'Healthcare', 'Diagnostics & Research', 1, 0.01, NULL),
('RMD', 'ResMed Inc.', 'NYSE', 'Healthcare', 'Medical Instruments & Supplies', 1, 0.01, NULL),
('WST', 'West Pharmaceutical Services, Inc.', 'NYSE', 'Healthcare', 'Medical Instruments & Supplies', 1, 0.01, NULL),
('PKI', NULL, NULL, NULL, NULL, 1, 0.01, NULL),
('HSY', 'The Hershey Company', 'NYSE', 'Consumer Defensive', 'Confectioners', 1, 0.01, NULL),
('K', NULL, NULL, NULL, NULL, 1, 0.01, NULL),
('GIS', 'General Mills, Inc.', 'NYSE', 'Consumer Defensive', 'Packaged Foods', 1, 0.01, NULL),
('CPB', 'The Campbell''s Company', 'NASDAQ', 'Consumer Defensive', 'Packaged Foods', 1, 0.01, NULL);
